# CONFIGURATION ONLY FOR DEVELOPERS

# component name
db:
  # schema name
  default:
    adapter: mysql
    host: localhost
    username: root
    password: 123321
    dbname: phpdays
engine:
  # collect debug info (1 - enable, 0 - disable)
  debug: 1
  # enable autorun files from the folder app/autorun (1 - enable, 0 - disable)
  autorun: 1
log:
  # show debug info into: firephp, file, sqlite
  type: firephp
  # show errors only with specified levels (levels joided by "bytes or")
  level: 31
url:
  lang: ru
  ext: html
  base: phpdays.org
  virtual: true
view:
  engine: smarty
cache:
  # cache data on this time (in seconds)
  lifetime: 0