# CONFIGURATION ONLY FOR DEVELOPERS

# component name
db:
  # schema name
  default:
    adapter: mysql
    host: localhost
    username: root
    password: 123321
    dbname: phpdays
engine:
  # collect debug info (1 - enable, 0 - disable)
  debug: 1
  # name of you brand (prefix for model classes)
  brand: app
log:
  # show debug info into: firephp, file, sqlite, browser
  type: browser
  # show errors only with specified levels (levels joided by "bytes or")
  level: 31
url:
  lang: ru
  ext: html
  # base path (need if site installed not in root directory)
  base:
view:
  engine: php
cache:
  # cache data on this time (in seconds)
  lifetime: 0